### ISSUE TITLE
Singleboostr.exe flagged by AV

### ISSUE THREAD

**Issue by HairyMilkshakes** [Ni1kko/HourBoostr#12]
I am sure it's a false positive but as FYI:

![2022-01-26_14-24-43](https://user-images.githubusercontent.com/13473043/151257832-306de40b-4bde-452f-a266-63d9246534a0.png)

**Comment by Ni1kko** [comment]
Source is public 1000% no malware. 
[If any would has any idea why this would of  ](https://www.virustotal.com/old-browsers/file-analysis/YWNmZmUxNWJkY2ExMjQ2ODYxNmZjMmEwMWM3MjNjODk6MTY0MzIzNjYzNg%3D%3D)

Kaspersky seems to be triggering i have done very little research but i believe that it could be our version check where i download the last version from github and check with current app version its the only thing i can see that could maybe cause it.

**Comment by HairyMilkshakes** [comment]
I'll just whitelist it - very odd since I've been running your program for the longest time and the AV's flagged it just today.

**Comment by Ni1kko** [comment]
whitelist is only temp solving the issue for you this need to be fixed globaly for everyone, i will change things and test it this will get sorted properly, i'm going reopen this so everyone can see this!

**Comment by HairyMilkshakes** [comment]
Here are the exceptions that I had to create (so far). 
![16158659 480000002_2022-01-26_19-50-46](https://user-images.githubusercontent.com/13473043/151289059-2d3f2fb6-7dde-44b6-8d70-52bf0c5e4d14.png)

**Comment by Ni1kko** [comment]
Kaspersky is no longer an issue but virus total is now saying microsoft is an issue https://www.virustotal.com/gui/file/22cd6cd2223f7951de66092e8961fa19d7f56cf87ad7866902a96dd6a993c29f?nocache=1

**Comment by Ni1kko** [comment]
All Fixed. Will publish new version in the morning im very tired just now. https://www.virustotal.com/gui/file/9bcddadf6692edd233125b21bb4012166442d53a02bed0909ad242e48347004f?nocache=1

**Comment by HairyMilkshakes** [comment]
Hi, it's starting to get flagged again by my AV:

![2022-02-23_23-24-53](https://user-images.githubusercontent.com/13473043/155477577-a10bd500-c3d6-4ca5-98c0-d8b164f254a8.png)
