### ISSUE TITLE
HourBoostr v4.3.0 no "User Authenticated" message

### ISSUE THREAD

**Issue by kadewu1** [Ni1kko/HourBoostr#18]
Since i'm using latest version (v4.3.0 as of now) i don't get "User Authenticated" message, even though i was getting it in older versions. Here are my settings (they are the same on both accounts)
![image](https://user-images.githubusercontent.com/68354192/151835737-41f0b5d9-03c3-4c5b-8dec-1528fdba637b.png)
![image](https://user-images.githubusercontent.com/68354192/151835794-c7a25e0e-13d3-49cb-a3b0-ca085ad617aa.png)

**Comment by kadewu1** [comment]
Happens only when there are two accounts added.

**Comment by Ni1kko** [comment]
give it a little time (10 mins) it may have failed first attempt and will be on sleep and will keep trying it should appear.
i have it loaded just now https://i.imgur.com/Tr11h4v.png

**Comment by kadewu1** [comment]
Yes, it works great on one account loaded, but it doesn't on two

**Comment by Ni1kko** [comment]
![pre](https://i.imgur.com/Zxf0cck.png)

im going to look in to the error i received. i can't replicate the issue you are saying as you can see its working at myside i started and left it for few mins and connected

**Comment by kadewu1** [comment]
![image](https://user-images.githubusercontent.com/68354192/151842366-c06264d6-6a7f-4766-84f9-49e826c6c08b.png)
running for 10 minutes still not connected, do hours still count?

**Comment by Ni1kko** [comment]
try re-start boostr see if that make a difference. alot of this code does need updated.

**Comment by Ni1kko** [comment]
![pre](https://i.imgur.com/ydTHpiX.png)
Testing new update will push release in the morning once i have tested for 6hrs

**Comment by Ni1kko** [comment]
If you want to test 4.3.1 too before i release it here is the files [release.zip](https://github.com/Ni1kko/HourBoostr/files/7975789/release.zip)

**Comment by kadewu1** [comment]
Hey, it works good but it doesn't ask for steam guard - it just keeps spamming my phone with notifications from steam 
![image](https://user-images.githubusercontent.com/68354192/151926185-fc990f5c-5480-4410-9feb-169a56557443.png)

**Comment by kadewu1** [comment]
Hey, i think i know what the problem is. I does not authenticate only when i launch it immediately after closing csgo or any other game on my pc. I need to wait like 10 minutes before launching HourBoostr and then everything works fine

**Comment by kadewu1** [comment]
for people encountering this problem in future: read the thing above and use version 4.3.1 (listed above if not available yet) or the newest one.

**Comment by Ni1kko** [comment]
Sorry I have been real busy with work and not had a chance to get to my pc and work on this. I have not forgotten about the issue just delayed at being able to fix due to lack of time but I will get around too it soon I have a few updates to push but I was wanting to test further first
